name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # make HEAD present
      # Currently no way to do this with actions/checkout: https://github.com/actions/checkout/issues/578
      - name: Checkout Master Branch
        run: git fetch origin master --no-tags --depth=1
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install Dependencies and Bootstrap
        run: npm run bootstrap
      - name: Debug Branches
        run: npm run list-changed
      - name: Lint PR
        # For PRs, run lint only on the changed files
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run lint-pr
      - name: Lint Repo
        # For pushes directly to master, run lint on the whole repo
        if: ${{ github.event_name == 'push' }}
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - lts/*
          - lts/-1

    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout Master Branch
        run: git fetch origin master --no-tags --depth=1
      - name: Checkout Submodules
        run: git submodule sync
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Dependencies and Bootstrap
        run: npm run bootstrap
      - name: Test PR
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run test-pr # we don't have anything that warrants a JUnit test file yet
      - name: Test Repo
        if: ${{ github.event_name == 'push' }}
        run: npm test
